name: Build Rescuezilla ARM64 ISO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-arm64-iso:
    runs-on: ubuntu-22.04-arm
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -f git-lfs git make sudo \
                         rsync debootstrap gettext squashfs-tools dosfstools mtools xorriso util-linux\
                         devscripts debhelper checkinstall cmake time parallel  dpkg-dev partclone\
                         grub-efi-arm64-bin \
                         shim-signed grub-efi-arm64-signed build-essential\
                         libtool-bin gawk pkg-config comerr-dev docbook-xsl e2fslibs-dev fuse3 \
                         libaal-dev libblkid-dev libbsd-dev libncurses5-dev \
                         libncursesw5-dev libntfs-3g89 libreadline-dev libreadline8 readline-common \
                         libreiser4-dev libtinfo-dev libxslt1.1 nilfs-tools ntfs-3g ntfs-3g-dev \
                         quilt sgml-base uuid-dev vmfs-tools xfslibs-dev xfsprogs xml-core \
                         xsltproc ccache libssl-dev
        gcc --version
        #dpkg -L partclone
        #sudo apt install gcc-9 g++-9
        #sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
        #sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
        #sudo update-alternatives --config gcc
        #sudo update-alternatives --config g++
        #which partclone
                         
    - name: Initialize submodules
      run: |
        git lfs clone https://github.com/nnhq/rescuezilla
        #cd rescuezilla/
        git submodule update --init --recursive
        #git submodule init
        #git submodule update --recursive

        
    - name: Build ISO
      run: |
        # Build the amd64 ISO image based on Ubuntu 20.04 (Focal), and the deb files.
        # This should work on Ubuntu or Ubuntu-derived distributions, but is _not_ recommended
        # Debian or Debian-derived environments (see "EFI Secure Boot" section below).
        sudo make jammy
        
    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: rescuezilla-arm64.iso
        path: rescuezilla/rescuezilla-arm64.iso
